src/components/NewTripScreen/NewTrip.js
Reverts GeoTogether/GeoTogether-Mobile-Application#7
=> Revert "This adds the SMS and Email invitation to Trip Add."

src/components/LoginScreen/Login.js, src/components/SignUpScreen/SignUp.js, src/components/TripsScreen/Trips.js, src/routes.js
=> intro and login fix

src/components/ProfileSettingsScreen/ProfileSettings.js
made the profile settings screen look more like the prototype
=> Us#88 task#141 benji

.gitignore, src/components/LoginScreen/Login.js, src/components/ProfileSettingsScreen/ProfileSettings.js, src/routes.js
fixing the facebook login and profile
=> fixing the facebook login and profile

.gitignore
=> fix  package

android/local.properties, package.json, src/components/MapViewScreen/GMapView.js, src/components/NewEventScreen/NewEvent.js, src/components/NewTripScreen/NewTrip.js
=> Us#9 task#156

src/components/NewTripScreen/NewTrip.js
Updated the look and feel of the Adding Trip screen, now it looks like the prototype just without the navigation
=> Updated the look and feel of the screen according to the prototype

src/components/NewTripScreen/NewTrip.js, src/routes.js
adding the new event screen to the routes
=> adding the new event screen to the routes

package.json, src/components/NewEventScreen/NewEvent.js, src/components/NewTripScreen/NewTrip.js
autocomplete the address for the events and the trip destinations
=> autocomplete the address for the events and the trip destinations

src/components/PasswordResetScreen/PasswordReset.js
Finished the task, improved the password reset screen.
=> Us#180 task#194 benji

src/components/NewTripScreen/NewTrip.js
mahdialharbi Updated the look of the New Trip Screen
=> mahdialharbi Updated the look of the New Trip Screen

src/components/TimelineScreen/TimeLineScreen.js
This will now display the new event. Still waiting to get the sponsor approval for the looks.
=> Us#8 task#163

src/components/LoginScreen/Login.js, src/components/NewEventScreen/NewEvent.js, src/components/NewTripScreen/NewTrip.js, src/components/PasswordResetScreen/PasswordReset.js, src/components/SignUpScreen/SignUp.js
added input validation for sign up, new trip, new event, and password reset. Task is complete
=> Us#180 task#195 benji

src/components/LoginScreen/Login.js, src/components/NewEventScreen/NewEvent.js, src/components/NewTripScreen/NewTrip.js, src/components/PasswordResetScreen/PasswordReset.js, src/components/SignUpScreen/SignUp.js
Reverts GeoTogether/GeoTogether-Mobile-Application#46
=> Revert "Us#180 task#195 benji"

src/components/ChatScreen/Chat.js, src/components/LoginScreen/Login.js, src/components/NewEventScreen/NewEvent.js, src/components/TripsScreen/Trips.js
Reverts GeoTogether/GeoTogether-Mobile-Application#54
=> Revert "Us#196 task#214"

src/components/MapViewScreen/GMapView.js, src/components/NewEventScreen/NewEvent.js, src/components/NewTripScreen/NewTrip.js
fixing the marker do not shwoing in the map
=> fixing the marker do not shwoing in the map

src/components/MapViewScreen/GMapView.js, src/components/NewEventScreen/NewEvent.js, src/components/TimelineScreen/TimeLineScreen.js, src/components/TripsScreen/Trips.js
Fixed the style for the action bar
=> Fixed the style for the action bar

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/geotogetherapplication/MainApplication.java, android/settings.gradle, package.json, src/components/ChatScreen/Chat.js, src/components/ChatScreen/ChatScreen.js, src/components/Custom/CustomActions.js, src/components/NewEventScreen/NewEvent.js, src/components/NewTripScreen/NewTrip.js, src/components/ProfileSettingsScreen/ProfileSettings.js, src/components/TripsScreen/Trips.js, src/routes.js
=> adding the chat to the master

src/components/ChatScreen/ChatScreen.js
adding action bar to the chat screen
=> adding action bar to the chat screen

src/components/IntroScreen/Swiper.js, src/components/SignUpScreen/SignUp.js
This put in correct input validation for sign up and fixed the intro app screen bug
=> Task#246_Benji

src/components/MapViewScreen/GMapView.js, src/components/TimelineScreen/TimeLineScreen.js
adding the icons to the timeline and fix the style for the map
=> adding the icons to the timeline and fix the style for the map

android/app/build.gradle, android/app/src/main/java/com/geotogetherapplication/MainApplication.java, android/settings.gradle, ios/GeoTogetherApplication.xcodeproj/project.pbxproj, ios/Podfile, ios/Podfile.lock, src/components/LoadingScreen/LoadingScreen.js, src/routes.js
adding loadingScreen and linking the package for ios
=> adding loadingScreen and linking the package for ios

android/app/build.gradle, android/app/src/main/java/com/geotogetherapplication/MainApplication.java, android/settings.gradle
=> fix the linking for android

src/components/ChatScreen/Chat.js, src/components/ChatScreen/ChatScreen.js, src/components/MapViewScreen/GMapView.js, src/components/SettingsScreen/AppSettings.js, src/components/ShareScreen/Share.js, src/components/TripsScreen/Trips.js
Update to advertisement handling in screens.
=> Advertisement test

android/local.properties, src/components/ChatScreen/ChatScreen.js, src/components/NewTripScreen/NewTrip.js
adding the invite members to the chat and remove it from new trip
=> adding the invite members to the chat and remove it from new trip

src/components/ChatScreen/ChatScreen.js
=> adding the sms invite option

src/components/MapViewScreen/GMapView.js
=> fixing the user location icon
